INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Lindsay','Colleen','P','01/09/1985','Tincidunt Tempus Limited','Anchorage'),('Singleton','Amela','Y','09/09/1994','Massa Industries','Napier'),('Holt','Chanda','Q','02/17/1988','Nisi Dictum Augue Corporation','Stendal'),('Harrington','Hayes','R','10/04/1986','Mauris Institute','Pogliano Milanese'),('Wise','Anne','U','10/10/1992','Enim Mauris Limited','Westkapelle'),('Summers','Jenette','B','03/09/1993','Facilisis Lorem Tristique Industries','Patalillo'),('Holcomb','Anthony','Y','09/14/1988','Nisi Cum Corporation','Rouvreux'),('Holt','Julian','U','12/30/1995','Dolor Quisque Inc.','Tampa'),('Miller','Kylie','E','09/17/1993','Mus Proin Vel LLP','Castelnuovo Magra'),('Horn','Kyla','C','05/07/1982','Eu Erat Semper LLP','Bhimavaram');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Ross','Geoffrey','L','02/27/1986','Fermentum LLP','Thines'),('Grant','Quentin','N','11/22/1993','Nunc Ac Ltd','Driekapellen'),('Mendez','Cameron','M','01/13/1992','Nibh Enim Gravida LLC','Coassolo Torinese'),('May','Porter','E','11/21/1988','Et Malesuada Fames Associates','Kozhikode'),('Tucker','Jocelyn','Q','05/21/1986','Parturient Montes Corp.','Bridge of Allan'),('Hester','Kylan','A','02/08/1990','Facilisis Magna Inc.','Anamur'),('Walker','Ignatius','K','11/28/1990','Sit Amet Institute','Lewiston'),('Espinoza','Hanae','D','03/29/1983','Aenean Euismod Corporation','Málaga'),('Schultz','Uriel','V','10/21/1991','Non Massa Non Associates','Los Andes'),('Delacruz','Dolan','P','03/04/1995','Cursus A Institute','Birmingham');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Collier','Nathaniel','N','10/21/1982','Mauris Eu Elit Associates','Armo'),('Gould','Upton','R','03/24/1983','Auctor Mauris Foundation','Comblain-Fairon'),('Mccoy','Brady','D','05/11/1994','Interdum Libero Dui PC','Straubing'),('Donovan','Sybill','G','07/23/1986','Eleifend Foundation','Ceuta'),('Randall','Jesse','A','07/10/1988','Vel Inc.','Ödemiş'),('Petty','Ignatius','K','11/29/1995','Sit Amet LLP','Sète'),('Graves','Jermaine','S','07/01/1993','Pede Nonummy Limited','Schleswig'),('Griffin','Wayne','T','12/05/1994','Per Conubia Foundation','Spijkenisse'),('Avila','Ann','O','06/18/1986','At Sem Corporation','Darwin'),('Waters','Tamekah','E','07/23/1995','Arcu LLP','Trevignano Romano');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Weiss','Garth','S','08/25/1981','Quisque Varius LLP','Rosenheim'),('Bauer','Bert','V','01/01/1994','Fringilla Corporation','Combarbalá'),('Kirk','Phyllis','W','06/28/1996','Amet Associates','Tillet'),('Wooten','Tara','E','11/18/1986','Eget Dictum Placerat Corp.','Taltal'),('Sargent','Branden','Y','02/15/1981','Duis Ac Consulting','Porto Cesareo'),('Stewart','Cassandra','I','04/13/1981','Pede Cras Corp.','Kolkata'),('Barnes','Amela','M','06/21/1987','Placerat Orci Lacus Corporation','Diyarbakır'),('Myers','Lareina','X','05/26/1990','Eget Company','Sulzbach'),('Kaufman','Hyacinth','B','01/10/1987','Senectus Et Netus Institute','Villa Agnedo'),('Mccarthy','Eden','R','08/01/1995','Vel Pede Inc.','Bordeaux');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Glenn','Quinlan','N','08/07/1983','Eu Consulting','Newark'),('Cantrell','Dominique','I','07/08/1985','Nam Consulting','Conselice'),('Pearson','Hope','W','11/22/1994','Lobortis Quam Corporation','Halesowen'),('Hansen','April','V','02/26/1991','Nulla Vulputate Associates','Springfield'),('Olson','Amery','D','10/20/1991','Aliquam Erat Limited','Bolinne'),('Cannon','Ulric','P','05/08/1989','Fusce Aliquam Enim Institute','Armadale'),('Mays','Colton','T','04/18/1986','Luctus Lobortis Class Associates','Siddi'),('Lawson','Azalia','R','06/01/1984','Libero Nec Limited','Heist-op-den-Berg'),('Burton','Chelsea','F','07/13/1996','Ut LLC','Trowbridge'),('Prince','Kelsie','J','02/28/1981','Cursus Company','Pozo Almonte');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Chan','Uma','P','03/13/1985','Quam A Felis Limited','Kano'),('Clark','Linda','T','10/07/1988','Dolor Industries','Bremerhaven'),('Jackson','Isabelle','G','05/13/1990','Quisque Fringilla Consulting','Lethbridge'),('Carrillo','Omar','Q','12/13/1980','Sed Nulla Limited','Zedelgem'),('Nielsen','Lacey','D','11/10/1994','Nam Inc.','Saint-Hilarion'),('Velazquez','Nissim','E','10/29/1985','Et Ipsum Limited','Vielsalm'),('Burris','Alma','M','06/13/1985','Dui Corporation','Lacombe County'),('Reilly','Wynne','R','06/24/1982','Sit Amet Metus Limited','Illapel'),('Medina','Kalia','V','10/27/1982','Euismod Enim Corp.','Nampa'),('Haley','Jason','Z','11/11/1980','Libero Lacus Varius Corporation','Rio nell''Elba');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Stout','Noelani','M','06/08/1988','Vehicula Aliquet Libero PC','Pietragalla'),('Johnston','Sybill','C','11/06/1995','Nunc Associates','Cleveland'),('Ruiz','Eden','D','04/02/1986','Suspendisse PC','Lac Ste. Anne'),('Richards','Fiona','W','04/05/1981','Curae; Phasellus Corporation','Westlock'),('Bond','Andrew','J','07/12/1994','Cras Consulting','Moliterno'),('Whitley','Quyn','Z','12/07/1987','Amet Ultricies Sem Incorporated','Tolve'),('Young','Troy','M','04/12/1991','Eu Associates','Treppo Carnico'),('Rodriquez','Conan','X','06/17/1988','Hendrerit Donec Porttitor Consulting','Camaçari'),('Mann','Zephr','J','04/06/1987','Sed Et Institute','Banbury'),('Rocha','Raven','A','07/13/1991','Fusce Mollis Duis Industries','Madison');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Ross','Stephen','R','01/09/1985','Nascetur PC','Dewas'),('Stein','Leigh','D','04/20/1982','Aliquet Odio Industries','l''Escaillre'),('Berger','Melvin','C','01/01/1996','Lectus Sit Amet Associates','Gillette'),('Love','Victor','Y','04/24/1983','Fusce Feugiat Consulting','Puyehue'),('Weiss','Althea','J','08/17/1982','Aliquam Adipiscing Consulting','Poederlee'),('Sanford','Blossom','K','02/09/1985','Ullamcorper Limited','San Pietro Avellana'),('Holden','Kennan','L','05/09/1991','At Ltd','Miami'),('Jones','Jena','S','09/10/1984','Blandit Corp.','Avadi'),('Moody','Quinlan','L','08/20/1993','Magna Limited','Irricana'),('Whitley','Asher','T','01/15/1988','Accumsan Convallis Ante Inc.','Merchtem');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Shepherd','Kiara','N','03/17/1993','Massa Consulting','Palmerston'),('Haynes','Maya','S','06/26/1994','Et Ultrices Posuere PC','Palencia'),('Richardson','Xandra','I','10/27/1987','Vitae Institute','Fosses-la-Ville'),('Mclean','Aladdin','K','10/04/1985','Nullam Lobortis Institute','Owensboro'),('Blankenship','Abigail','A','07/16/1993','Dis Parturient Montes Company','Cassano Spinola'),('Barr','Ariana','J','05/09/1990','Enim Limited','Isla de Maipo'),('Hyde','Kessie','H','12/07/1983','Vulputate Eu Inc.','Monticelli d''Ongina'),('Oneal','Inga','Q','12/10/1984','Sed Nec Metus Ltd','Sint-Martens-Bodegem'),('Graves','Peter','J','05/28/1984','Eget Volutpat LLP','Nieuwkapelle'),('Velasquez','Karyn','K','08/16/1988','Phasellus Dolor Ltd','Nemoli');
INSERT INTO Contacts([Surname],[Name],[Patronymic],[Birthday],[Organization],[Position]) VALUES('Frost','Rahim','E','05/03/1985','Vitae Company','Turgutlu'),('Walton','Allegra','L','09/21/1994','Ipsum Leo Corporation','Karnal'),('Wynn','Andrew','W','05/26/1988','Orci In Incorporated','Vollezele'),('Mcdonald','Ross','I','06/11/1993','Ut Industries','Chicoutimi'),('Crawford','Melissa','N','11/27/1987','Dignissim Corp.','Guardia Perticara'),('Rodgers','Kirestin','X','10/13/1981','A Neque Consulting','Saarlouis'),('Glover','Sara','Z','08/16/1982','Lorem Incorporated','Guilmi'),('Hopper','Stella','D','10/21/1995','Risus Corporation','Sant''Angelo a Cupolo'),('Ortega','Arthur','U','06/07/1995','Lorem Luctus LLC','Itapipoca'),('Herman','Mercedes','I','08/15/1995','Sed Facilisis Vitae LLP','San Javier');

--id between 3 and 102:
UPDATE Contacts SET Surname = N'Шаньгин',Name = N'Якуб',Patronymic = N'Феликсович' WHERE Id= 101;
UPDATE Contacts SET Surname = N'Кошляк',Name = N'Тихон',Patronymic = N'Трофимович' WHERE Id= 102;
UPDATE Contacts SET Surname = N'Ахременко',Name = N'Игнатий',Patronymic = N'Моисеевич' WHERE Id= 3;
UPDATE Contacts SET Surname = N'Берестова',Name = N'Виктория',Patronymic = N'Афанасиевна' WHERE Id= 4;
UPDATE Contacts SET Surname = N'Разин',Name = N'Иннокентий',Patronymic = N'Архипович' WHERE Id= 5;
UPDATE Contacts SET Surname = N'Райта',Name = N'Александра',Patronymic = N'Захаровна' WHERE Id= 6;
UPDATE Contacts SET Surname = N'Яхонтов',Name = N'Рубен',Patronymic = N'Иннокентиевич' WHERE Id= 7;
UPDATE Contacts SET Surname = N'Комбаров',Name = N'Нестор',Patronymic = N'Ульянович' WHERE Id= 8;
UPDATE Contacts SET Surname = N'Танкова',Name = N'Кристина',Patronymic = N'Родионовна' WHERE Id= 9;
UPDATE Contacts SET Surname = N'Жаглин',Name = N'Евдоким',Patronymic = N'Елизарович' WHERE Id= 10;
UPDATE Contacts SET Surname = N'Арсеньев',Name = N'Артур',Patronymic = N'Артемович' WHERE Id= 11;
UPDATE Contacts SET Surname = N'Тукаева',Name = N'Алина',Patronymic = N'Иосифовна' WHERE Id= 12;
UPDATE Contacts SET Surname = N'Камалова',Name = N'Ульяна',Patronymic = N'Святославовна' WHERE Id= 13;
UPDATE Contacts SET Surname = N'Щепетинникова',Name = N'Евгения',Patronymic = N'Федоровна' WHERE Id= 14;
UPDATE Contacts SET Surname = N'Усов',Name = N'Марк',Patronymic = N'Андреевич' WHERE Id= 15;
UPDATE Contacts SET Surname = N'Кузуба',Name = N'Доминика',Patronymic = N'Давидовна' WHERE Id= 16;
UPDATE Contacts SET Surname = N'Гик',Name = N'Лавр',Patronymic = N'Аникитевич' WHERE Id= 17;
UPDATE Contacts SET Surname = N'Грефа',Name = N'Пелагея',Patronymic = N'Мефодиевна' WHERE Id= 18;
UPDATE Contacts SET Surname = N'Баева',Name = N'Святослав',Patronymic = N'Проклович' WHERE Id= 19;
UPDATE Contacts SET Surname = N'Грешнев',Name = N'Чеслав',Patronymic = N'Ульянович' WHERE Id= 20;
UPDATE Contacts SET Surname = N'Битнера',Name = N'Светлана',Patronymic = NULL WHERE Id= 21;
UPDATE Contacts SET Surname = N'Усова',Name = N'Милена',Patronymic = N'Казимировна' WHERE Id= 22;
UPDATE Contacts SET Surname = N'Смехова',Name = N'Кристина',Patronymic = N'Афанасиевна' WHERE Id= 23;
UPDATE Contacts SET Surname = N'Головнина',Name = N'Инесса',Patronymic = N'Александровна' WHERE Id= 24;
UPDATE Contacts SET Surname = N'Смольников',Name = N'Осип',Patronymic = N'Герасимович' WHERE Id= 25;
UPDATE Contacts SET Surname = N'Юханцев',Name = N'Николай',Patronymic = N'Эмилевич' WHERE Id= 26;
UPDATE Contacts SET Surname = N'Жиленков',Name = N'Богдан',Patronymic = N'Онисимович' WHERE Id= 27;
UPDATE Contacts SET Surname = N'Парфёнов',Name = N'Никанор',Patronymic = N'Ерофеевич' WHERE Id= 28;
UPDATE Contacts SET Surname = N'Битнера',Name = N'Элеонора',Patronymic = N'Леонидовна' WHERE Id= 29;
UPDATE Contacts SET Surname = N'Шибалкина',Name = N'Лариса',Patronymic = N'Михеевна' WHERE Id= 30;
UPDATE Contacts SET Surname = N'Валеев',Name = N'Ким',Patronymic = N'Капитонович' WHERE Id= 31;
UPDATE Contacts SET Surname = N'Канаша',Name = N'Пелагея',Patronymic = N'Владиленовна' WHERE Id= 32;
UPDATE Contacts SET Surname = N'Лысова',Name = N'Наталья',Patronymic = N'Якововна' WHERE Id= 33;
UPDATE Contacts SET Surname = N'Кутузов',Name = N'Валерьян',Patronymic = N'Олегович' WHERE Id= 34;
UPDATE Contacts SET Surname = N'Шелепов',Name = N'Елисей',Patronymic = N'Тарасович' WHERE Id= 35;
UPDATE Contacts SET Surname = N'Петрова',Name = N'Тамара',Patronymic = N'Филипповна' WHERE Id= 36;
UPDATE Contacts SET Surname = N'Убыша',Name = N'Юнона',Patronymic = N'Владленовна' WHERE Id= 37;
UPDATE Contacts SET Surname = N'Митрофанов',Name = N'Никифор',Patronymic = N'Ростиславович' WHERE Id= 38;
UPDATE Contacts SET Surname = N'Дульцев',Name = N'Гавриил',Patronymic = N'Моисеевич' WHERE Id= 39;
UPDATE Contacts SET Surname = N'Разуваева',Name = N'Эльвира',Patronymic = N'Филипповна' WHERE Id= 40;
UPDATE Contacts SET Surname = N'Макаров',Name = N'Порфирий',Patronymic = N'Демьянович' WHERE Id= 41;
UPDATE Contacts SET Surname = N'Корявова',Name = N'Светлана',Patronymic = N'Романовна' WHERE Id= 42;
UPDATE Contacts SET Surname = N'Энгалычева',Name = N'Анисья',Patronymic = N'Романовна' WHERE Id= 43;
UPDATE Contacts SET Surname = N'Маховицкий',Name = N'Адам',Patronymic = N'Несторович' WHERE Id= 44;
UPDATE Contacts SET Surname = N'Никерхоева',Name = N'Бронислава',Patronymic = N'Серафимовна' WHERE Id= 45;
UPDATE Contacts SET Surname = N'Апевалов',Name = N'Демьян',Patronymic = N'Дмитриевич' WHERE Id= 46;
UPDATE Contacts SET Surname = N'Гурьянова',Name = N'Евгения',Patronymic = N'Олеговна' WHERE Id= 47;
UPDATE Contacts SET Surname = N'Лисов',Name = N'Петр',Patronymic = N'Панкратиевич' WHERE Id= 48;
UPDATE Contacts SET Surname = N'Набутов',Name = N'Андрей',Patronymic = N'Федотович' WHERE Id= 49;
UPDATE Contacts SET Surname = N'Скотарева',Name = N'Кристина',Patronymic = N'Федотовна' WHERE Id= 50;
UPDATE Contacts SET Surname = N'Юсупова',Name = N'Татьяна',Patronymic = N'Леонидовна' WHERE Id= 51;
UPDATE Contacts SET Surname = N'Кугушев',Name = N'Афанасий',Patronymic = N'Валериевич' WHERE Id= 52;
UPDATE Contacts SET Surname = N'Рождественский',Name = N'Харитон',Patronymic = N'Адрианович' WHERE Id= 53;
UPDATE Contacts SET Surname = N'Черенчикова',Name = N'Кира',Patronymic = N'Тихоновна' WHERE Id= 54;
UPDATE Contacts SET Surname = N'Сомова',Name = N'Рада',Patronymic = N'Данииловна' WHERE Id= 55;
UPDATE Contacts SET Surname = N'Ильина',Name = N'Лиана',Patronymic = N'Георгиевна' WHERE Id= 56;
UPDATE Contacts SET Surname = N'Нагибина',Name = N'Яна',Patronymic = N'Фомевна' WHERE Id= 57;
UPDATE Contacts SET Surname = N'Прилуцкий',Name = N'Давид',Patronymic = N'Изяславович' WHERE Id= 58;
UPDATE Contacts SET Surname = N'Стукалов',Name = N'Антип',Patronymic = N'Феликсович' WHERE Id= 59;
UPDATE Contacts SET Surname = N'Новичков',Name = N'Федор',Patronymic = N'Кондратиевич' WHERE Id= 60;
UPDATE Contacts SET Surname = N'Лагутин',Name = N'Яков',Patronymic = N'Якубович' WHERE Id= 61;
UPDATE Contacts SET Surname = N'Добрынина',Name = N'Юнона',Patronymic = N'Семеновна' WHERE Id= 62;
UPDATE Contacts SET Surname = N'Коршунова',Name = N'Анна',Patronymic = N'Олеговна' WHERE Id= 63;
UPDATE Contacts SET Surname = N'Хлопонина',Name = N'Вероника',Patronymic = N'Емельяновна' WHERE Id= 64;
UPDATE Contacts SET Surname = N'Максимушкин',Name = N'Тимур',Patronymic = N'Федотович' WHERE Id= 65;
UPDATE Contacts SET Surname = N'Евстигнеев',Name = N'Пахом',Patronymic = N'Платонович' WHERE Id= 66;
UPDATE Contacts SET Surname = N'Гребенщикова',Name = N'Стела',Patronymic = N'Германовна' WHERE Id= 67;
UPDATE Contacts SET Surname = N'Рыбьяков',Name = N'Борис',Patronymic = N'Дмитриевич' WHERE Id= 68;
UPDATE Contacts SET Surname = N'Яковиченко',Name = N'Аристарх',Patronymic = N'Тихонович' WHERE Id= 69;
UPDATE Contacts SET Surname = N'Пономарева',Name = N'Лада',Patronymic = N'Серафимовна' WHERE Id= 70;
UPDATE Contacts SET Surname = N'Аводкова',Name = N'Анфиса',Patronymic = N'Ираклиевна' WHERE Id= 71;
UPDATE Contacts SET Surname = N'Ясева',Name = N'Евдокия',Patronymic = N'Степановна' WHERE Id= 72;
UPDATE Contacts SET Surname = N'Остапчук',Name = N'Павел',Patronymic = N'Моисеевич' WHERE Id= 73;
UPDATE Contacts SET Surname = N'Колокольцов',Name = N'Парфен',Patronymic = N'Арсениевич' WHERE Id= 74;
UPDATE Contacts SET Surname = N'Турышев',Name = N'Прокофий',Patronymic = N'Касьянович' WHERE Id= 75;
UPDATE Contacts SET Surname = N'Приходько',Name = N'Анастасия',Patronymic = N'Всеволодовна' WHERE Id= 76;
UPDATE Contacts SET Surname = N'Сиянович',Name = N'Наум',Patronymic = N'Чеславович' WHERE Id= 77;
UPDATE Contacts SET Surname = N'Островерхова',Name = N'Вероника',Patronymic = N'Ираклиевна' WHERE Id= 78;
UPDATE Contacts SET Surname = N'Нугаева',Name = N'Ефросиния',Patronymic = N'Ипполитовна' WHERE Id= 79;
UPDATE Contacts SET Surname = N'Шакмакова',Name = N'Любовь',Patronymic = N'Афанасиевна' WHERE Id= 80;
UPDATE Contacts SET Surname = N'Берия',Name = N'Вероника',Patronymic = N'Серафимовна' WHERE Id= 81;
UPDATE Contacts SET Surname = N'Кадцын',Name = N'Елисей',Patronymic = N'Трофимович' WHERE Id= 82;
UPDATE Contacts SET Surname = N'Карданова',Name = N'Софья',Patronymic = N'Александровна' WHERE Id= 83;
UPDATE Contacts SET Surname = N'Усов',Name = N'Нестор',Patronymic = N'Трофимович' WHERE Id= 84;
UPDATE Contacts SET Surname = N'Цорна',Name = N'Галина',Patronymic = N'Марковна' WHERE Id= 85;
UPDATE Contacts SET Surname = N'Лубашев',Name = N'Моисей',Patronymic = N'Назарович' WHERE Id= 86;
UPDATE Contacts SET Surname = N'Трунина',Name = N'Екатерина',Patronymic = N'Фомевна' WHERE Id= 87;
UPDATE Contacts SET Surname = N'Хамидуллина',Name = N'Диана',Patronymic = N'Владленовна' WHERE Id= 88;
UPDATE Contacts SET Surname = N'Ляпина',Name = N'Вера',Patronymic = N'Тихоновна' WHERE Id= 89;
UPDATE Contacts SET Surname = N'Веточкина',Name = N'Эмма',Patronymic = N'Феликсовна' WHERE Id= 90;
UPDATE Contacts SET Surname = N'Ясенева',Name = N'Яна',Patronymic = N'Юлиевна' WHERE Id= 91;
UPDATE Contacts SET Surname = N'Старостина',Name = N'Роза',Patronymic = N'Тимуровна' WHERE Id= 92;
UPDATE Contacts SET Surname = N'Державина',Name = N'Арина',Patronymic = N'Романовна' WHERE Id= 93;
UPDATE Contacts SET Surname = N'Щавлев',Name = N'Сергей',Patronymic = N'Казимирович' WHERE Id= 94;
UPDATE Contacts SET Surname = N'Болокан',Name = N'Терентий',Patronymic = N'Севастьянович' WHERE Id= 95;
UPDATE Contacts SET Surname = N'Зощенко',Name = N'Олег',Patronymic = N'Семенович' WHERE Id= 96;
UPDATE Contacts SET Surname = N'Шапошников',Name = N'Адам',Patronymic = N'Демьянович' WHERE Id= 97;
UPDATE Contacts SET Surname = N'Шуличенко',Name = N'Екатерина',Patronymic = N'Кузьмевна' WHERE Id= 98;
UPDATE Contacts SET Surname = N'Седова',Name = N'Светлана',Patronymic = N'Глебовна' WHERE Id= 99;
UPDATE Contacts SET Surname = N'Коченков',Name = N'Осип',Patronymic = N'Ерофеевич' WHERE Id= 100;

UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 101;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 102;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 3;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 4;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 5;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 6;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 7;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 8;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 9;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 10;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 11;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 12;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 13;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 14;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 15;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 16;
UPDATE [Contacts] SET [Position] = 'Technical Support Engineer' WHERE [Id] = 17;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 18;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 19;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 20;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 21;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 22;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 23;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 24;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 25;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 26;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 27;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 28;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 29;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 30;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 31;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 32;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 33;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 34;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 35;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 36;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 37;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 38;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 39;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 40;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 41;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 42;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 43;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 44;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 45;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 46;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 47;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 48;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 49;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 50;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 51;
UPDATE [Contacts] SET [Position] = 'Technical Support Engineer' WHERE [Id] = 52;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 53;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 54;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 55;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 56;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 57;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 58;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 59;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 60;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 61;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 62;
UPDATE [Contacts] SET [Position] = 'Technical Support Engineer' WHERE [Id] = 63;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 64;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 65;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 66;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 67;
UPDATE [Contacts] SET [Position] = 'Technical Support Engineer' WHERE [Id] = 68;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 69;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 70;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 71;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 72;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 73;
UPDATE [Contacts] SET [Position] = 'Tester' WHERE [Id] = 74;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 75;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 76;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 77;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 78;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 79;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 80;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 81;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 82;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 83;
UPDATE [Contacts] SET [Position] = 'Senior Engineer' WHERE [Id] = 84;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 85;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 86;
UPDATE [Contacts] SET [Position] = 'Technical Support Engineer' WHERE [Id] = 87;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 88;
UPDATE [Contacts] SET [Position] = 'Chief Information Officer' WHERE [Id] = 89;
UPDATE [Contacts] SET [Position] = 'System Administrator' WHERE [Id] = 90;
UPDATE [Contacts] SET [Position] = 'System Engineer' WHERE [Id] = 91;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 92;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 93;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 94;
UPDATE [Contacts] SET [Position] = 'Chief Technology Officer' WHERE [Id] = 95;
UPDATE [Contacts] SET [Position] = 'Software Architect' WHERE [Id] = 96;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 97;
UPDATE [Contacts] SET [Position] = 'Software Developer' WHERE [Id] = 98;
UPDATE [Contacts] SET [Position] = 'Project Manager' WHERE [Id] = 99;
UPDATE [Contacts] SET [Position] = 'Team Leader' WHERE [Id] = 100;

--id between 3 and 102:
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(91,'Home','(105) 716-2438'),(17,'Work','(230) 620-4940'),(37,'Work','(735) 541-9309'),(40,'Work','(784) 346-1003'),(50,'Work','(616) 652-1057'),(35,'Work','(753) 312-7859'),(78,'Work','(468) 436-2521'),(36,'Work','(164) 993-3659'),(26,'Work','(616) 978-0678'),(54,'Work','(686) 979-2916');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(6,'Mobile','(120) 912-5498'),(12,'Mobile','(398) 704-9891'),(87,'Home','(872) 743-8842'),(94,'Work','(542) 320-7341'),(81,'Work','(225) 959-5887'),(9,'Mobile','(562) 565-5617'),(28,'Work','(437) 491-2160'),(6,'Work','(106) 478-5326'),(82,'Mobile','(558) 113-8455'),(63,'Home','(870) 701-8572');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(83,'Work','(368) 776-0524'),(41,'Work','(890) 861-8359'),(80,'Mobile','(479) 264-7353'),(66,'Work','(160) 997-8929'),(40,'Mobile','(932) 985-5117'),(56,'Work','(816) 913-1559'),(17,'Home','(486) 985-8193'),(54,'Mobile','(389) 855-7484'),(93,'Work','(713) 422-5677'),(19,'Work','(846) 601-1715');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(40,'Work','(125) 732-9944'),(14,'Mobile','(191) 928-2269'),(51,'Work','(967) 112-7357'),(6,'Mobile','(196) 437-8487'),(7,'Work','(877) 684-7506'),(69,'Work','(677) 190-8458'),(36,'Home','(443) 735-7080'),(69,'Home','(626) 539-6205'),(29,'Home','(259) 201-3128'),(9,'Work','(319) 744-8016');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(18,'Mobile','(735) 220-5481'),(14,'Work','(148) 290-4721'),(56,'Home','(284) 385-5505'),(52,'Work','(988) 465-9569'),(6,'Work','(160) 102-4657'),(12,'Mobile','(103) 390-3611'),(86,'Mobile','(609) 493-3148'),(57,'Mobile','(331) 301-0620'),(77,'Mobile','(471) 238-9509'),(76,'Mobile','(358) 891-1257');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(97,'Mobile','(778) 215-6544'),(69,'Work','(696) 694-0827'),(91,'Work','(858) 483-2404'),(23,'Work','(266) 700-0062'),(92,'Work','(637) 183-3334'),(98,'Home','(467) 529-0293'),(58,'Work','(756) 876-4038'),(96,'Work','(224) 293-0101'),(14,'Work','(272) 995-9160'),(35,'Mobile','(470) 377-3833');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(19,'Home','(304) 414-7233'),(57,'Mobile','(298) 313-3498'),(78,'Home','(506) 882-2609'),(17,'Home','(111) 199-4312'),(9,'Home','(552) 348-7418'),(10,'Work','(980) 320-6344'),(47,'Mobile','(964) 698-4290'),(75,'Mobile','(959) 771-8382'),(53,'Home','(627) 655-3088'),(42,'Work','(864) 705-5340');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(96,'Mobile','(560) 782-5092'),(67,'Work','(929) 149-3082'),(16,'Work','(859) 605-5080'),(21,'Mobile','(744) 945-9851'),(18,'Home','(238) 812-9807'),(33,'Work','(962) 895-2048'),(100,'Home','(893) 463-5251'),(25,'Mobile','(733) 762-8824'),(18,'Mobile','(453) 752-0247'),(64,'Work','(403) 561-7193');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(100,'Home','(673) 980-4795'),(8,'Mobile','(645) 521-4801'),(13,'Mobile','(423) 429-3936'),(59,'Mobile','(168) 293-4648'),(49,'Home','(833) 950-2569'),(45,'Mobile','(738) 752-2866'),(24,'Work','(809) 845-5687'),(57,'Mobile','(832) 686-5489'),(68,'Home','(680) 363-8745'),(14,'Mobile','(407) 340-2456');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(25,'Mobile','(656) 542-5982'),(87,'Home','(850) 758-7332'),(17,'Work','(536) 886-1864'),(95,'Mobile','(527) 815-4246'),(4,'Work','(984) 277-4059'),(37,'Mobile','(623) 952-5736'),(72,'Work','(322) 286-0289'),(73,'Work','(398) 912-9071'),(95,'Home','(341) 699-4194'),(95,'Mobile','(466) 793-2126');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(63,'Work','(308) 450-5684'),(93,'Mobile','(600) 909-0222'),(97,'Home','(881) 313-1020'),(15,'Mobile','(806) 393-0855'),(41,'Home','(594) 605-9518'),(48,'Mobile','(152) 924-7380'),(69,'Home','(149) 479-7709'),(58,'Mobile','(887) 851-6211'),(80,'Work','(799) 874-6702'),(4,'Mobile','(661) 569-2499');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(18,'Home','(667) 947-0080'),(71,'Work','(131) 179-4848'),(6,'Work','(574) 741-0909'),(14,'Mobile','(404) 452-1480'),(80,'Work','(114) 186-6268'),(6,'Work','(679) 905-1201'),(68,'Home','(875) 349-9439'),(92,'Home','(984) 665-3040'),(57,'Work','(997) 600-3766'),(69,'Home','(293) 332-9761');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(97,'Home','(867) 995-0024'),(85,'Work','(695) 246-7395'),(94,'Mobile','(105) 565-0614'),(14,'Work','(859) 600-7548'),(83,'Work','(965) 103-4693'),(79,'Home','(222) 479-9510'),(4,'Mobile','(258) 183-9855'),(100,'Work','(827) 282-0534'),(17,'Home','(322) 267-9371'),(7,'Mobile','(961) 726-2248');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(75,'Home','(709) 509-5569'),(86,'Work','(843) 553-6832'),(26,'Work','(553) 943-2260'),(67,'Work','(110) 895-6250'),(77,'Work','(322) 267-7559'),(93,'Work','(735) 276-7308'),(38,'Home','(900) 156-9586'),(57,'Home','(774) 958-1478'),(76,'Home','(427) 926-9152'),(17,'Mobile','(797) 334-4283');
INSERT INTO ContactsPhones([ContactId],[Type],[Phone]) VALUES(86,'Work','(729) 608-7579'),(18,'Home','(326) 859-3126'),(36,'Home','(629) 938-5461'),(64,'Mobile','(681) 520-7857'),(29,'Work','(170) 179-8354'),(32,'Home','(761) 888-1498'),(34,'Mobile','(456) 477-9312'),(53,'Home','(226) 598-2059'),(90,'Work','(957) 317-5671'),(11,'Mobile','(208) 298-0072');

INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(42,'tortor.at.risus@semper.co.uk'),(51,'ornare.sagittis@idblanditat.edu'),(62,'mattis.semper@lacusQuisquepurus.ca'),(15,'feugiat.Sed@Mauris.co.uk'),(18,'Nullam.ut@Nullafacilisis.edu'),(76,'non@nunc.net'),(39,'risus.quis@diameu.com'),(14,'odio.a@Integeraliquam.ca'),(69,'at.velit.Pellentesque@nasceturridiculusmus.co.uk'),(75,'mi@natoque.com');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(15,'elementum@utdolordapibus.com'),(48,'Sed.eu@viverraMaecenas.ca'),(42,'lorem@nec.org'),(23,'metus.vitae.velit@nec.ca'),(35,'magna.Sed@semPellentesqueut.org'),(27,'Curae.Donec.tincidunt@Cum.ca'),(35,'neque.et@Suspendissecommodotincidunt.edu'),(12,'ipsum.dolor@accumsan.net'),(63,'Proin@nullamagnamalesuada.com'),(52,'at.iaculis@laoreetposuereenim.net');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(68,'risus.Quisque.libero@quis.com'),(101,'mi.eleifend.egestas@tortor.com'),(85,'ridiculus.mus.Donec@Phasellusdapibusquam.edu'),(20,'dolor.dapibus.gravida@sapienCrasdolor.com'),(36,'nisi@pedePraesent.com'),(91,'nec.euismod.in@nisi.net'),(29,'sem@Morbinequetellus.net'),(43,'et.magnis@eget.edu'),(99,'dolor.sit@risusDonecegestas.co.uk'),(95,'velit.eget.laoreet@tempusloremfringilla.net');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(52,'vulputate@nequeMorbiquis.com'),(13,'luctus.Curabitur@lobortisultrices.net'),(58,'Vivamus@sit.org'),(81,'Maecenas.iaculis@leo.ca'),(90,'tincidunt@leoMorbineque.co.uk'),(86,'metus@anteNuncmauris.net'),(24,'sed.sapien.Nunc@ac.ca'),(68,'Sed.id.risus@atnisi.edu'),(11,'ultrices.a.auctor@lacusAliquam.com'),(85,'Donec@commodohendreritDonec.net');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(17,'Curabitur@libero.edu'),(29,'eleifend@ullamcorpernisl.net'),(15,'Quisque@velit.edu'),(90,'Integer.aliquam.adipiscing@ante.net'),(34,'mattis.Cras.eget@feugiat.co.uk'),(70,'diam.at@porttitorvulputateposuere.org'),(47,'iaculis@apurus.edu'),(33,'nunc.id@et.edu'),(32,'magna@Donecegestas.co.uk'),(69,'erat@eratin.com');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(56,'Mauris@pede.edu'),(90,'eu@tristiquesenectuset.com'),(53,'pede.nonummy@consectetueripsumnunc.co.uk'),(62,'faucibus.Morbi@Nam.co.uk'),(43,'nunc.nulla@risusDonecnibh.com'),(74,'ac.orci.Ut@aliquetliberoInteger.net'),(28,'Aliquam.nisl@nonummy.net'),(72,'mauris.Integer.sem@amet.co.uk'),(72,'luctus.Curabitur@at.com'),(98,'sollicitudin@condimentum.org');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(55,'dictum@Curae.co.uk'),(63,'massa.lobortis@ipsum.co.uk'),(94,'turpis.vitae.purus@euismod.edu'),(25,'Fusce@nonummy.org'),(28,'a.felis@orciluctus.com'),(16,'ullamcorper.viverra@nec.net'),(38,'arcu@ataugue.com'),(35,'ac@amagna.com'),(44,'consectetuer@etrutrum.net'),(74,'faucibus@lectusNullam.net');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(90,'Morbi.neque.tellus@Proin.ca'),(78,'neque.venenatis@mattisCraseget.net'),(86,'fringilla@orci.net'),(31,'leo.Cras.vehicula@ProindolorNulla.co.uk'),(15,'libero.mauris@venenatisamagna.net'),(40,'Proin@nonjustoProin.edu'),(59,'a.enim@consequatdolor.ca'),(50,'aliquet.vel@egetodio.net'),(31,'Suspendisse@nec.net'),(12,'nisi.nibh.lacinia@gravidaPraesenteu.com');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(36,'elit.elit@vitaevelitegestas.org'),(74,'a.arcu@etcommodoat.org'),(19,'interdum@Cras.org'),(60,'eu@temporestac.edu'),(75,'dui.nec@Namnulla.edu'),(92,'malesuada.fames.ac@metussit.edu'),(19,'commodo.ipsum.Suspendisse@Nullasempertellus.net'),(82,'pellentesque.massa@egestas.edu'),(38,'non@felispurusac.org'),(47,'vitae.erat@nec.co.uk');
INSERT INTO ContactsEmails([ContactId],[Email]) VALUES(83,'magnis.dis.parturient@justosit.net'),(33,'tortor@lobortis.co.uk'),(34,'velit.egestas.lacinia@atiaculis.edu'),(80,'massa.lobortis@id.net'),(43,'nunc@molestie.com'),(10,'natoque.penatibus.et@temporaugue.net'),(10,'auctor.velit.eget@nonmagna.co.uk'),(59,'accumsan@pede.net'),(25,'justo.faucibus.lectus@vel.edu'),(68,'hymenaeos.Mauris@anteipsum.ca');

INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(96,'A.Raj'),(73,'Krittika123'),(65,'O.Patel'),(76,'Singh.T'),(93,'Ilango123'),(6,'Raj.N'),(99,'Gulab123'),(92,'S.Kumar'),(85,'Rakesh123'),(74,'H.Raj');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(43,'H.Patel'),(63,'Patel.O'),(13,'Singh.F'),(74,'D.Singh'),(70,'Lochan123'),(4,'Urmila123'),(39,'xMandithx'),(64,'xDhavalx'),(39,'xSunasix'),(35,'Khan.D');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(82,'Gyanada123'),(94,'xPragunx'),(40,'Khan.G'),(98,'xYashx'),(22,'G.Jain'),(35,'Devasree123'),(11,'P.Khan'),(70,'Kanwalkishore123'),(86,'Raj.U'),(13,'Kumar.L');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(96,'Rehwa123'),(85,'Narayani123'),(82,'Patel.U'),(100,'K.Jain'),(8,'Ismail.T'),(86,'Madhulika123'),(83,'Hemendra123'),(98,'Manasa123'),(57,'xSanyuktax'),(88,'Darpak123');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(14,'xViplabx'),(23,'xTrivenix'),(45,'xManishax'),(65,'xJalendrax'),(22,'Jain.J'),(74,'xSudiptix'),(87,'M.Khan'),(40,'xRahasx'),(75,'Jagachandra123'),(39,'xBuddhadevax');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(19,'Y.Raj'),(24,'xFaridax'),(55,'Jain.Z'),(75,'Ankit123'),(32,'Kamalkali123'),(80,'Dharmanand123'),(25,'Jain.L'),(79,'xThenMolix'),(56,'xPrashantax'),(26,'xSudhindrax');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(65,'xQuarrtulainx'),(83,'Raj.Q'),(14,'Raj.O'),(10,'xFirozx'),(98,'Jaya123'),(21,'Y.Khan'),(80,'Kumar.G'),(40,'xJahnavix'),(55,'Z.Jain'),(61,'Kumar.W');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(44,'R.Patel'),(33,'xMadhurix'),(88,'Y.Khan'),(61,'Vinita123'),(57,'W.Kumar'),(5,'Patel.I'),(88,'S.Raj'),(6,'Jain.A'),(9,'xAdhipax'),(41,'Patel.K');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(76,'K.Ismail'),(88,'Triveni123'),(64,'Patel.L'),(7,'xDeepax'),(46,'xDarukax'),(9,'A.Singh'),(95,'xOviyax'),(13,'Ashis123'),(41,'xChangunax'),(5,'R.Ismail');
INSERT INTO ContactsSkypes([ContactId],[Skype]) VALUES(16,'Umrao123'),(45,'Jain.J'),(46,'Chitral123'),(51,'Kumar.J'),(97,'M.Raj'),(51,'xVaishalix'),(91,'U.Khan'),(89,'Patel.K'),(91,'Kumar.X'),(73,'xPadmalochanax');
UPDATE ContactsSkypes SET Skype = LOWER(Skype)

INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(11,'ipsum. Curabitur consequat, lectus'),(101,'nisl. Maecenas malesuada'),(88,'Duis a mi fringilla mi'),(57,'velit. Aliquam nisl. Nulla'),(65,'eget, venenatis a, magna. Lorem'),(81,'arcu. Vestibulum ante'),(66,'Nunc ullamcorper, velit'),(8,'dolor sit amet, consectetuer adipiscing'),(80,'lorem vitae odio sagittis semper.'),(30,'ullamcorper. Duis at');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(16,'amet ante. Vivamus'),(29,'mauris eu elit. Nulla'),(99,'Cum sociis natoque'),(97,'urna justo faucibus'),(20,'semper rutrum. Fusce dolor'),(6,'pede nec ante blandit'),(30,'sagittis. Nullam vitae'),(11,'montes, nascetur ridiculus mus.'),(43,'pede. Praesent eu dui.'),(81,'enim. Etiam imperdiet');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(57,'fringilla est. Mauris eu'),(7,'tristique pharetra. Quisque ac'),(69,'tellus. Nunc lectus pede,'),(33,'nec tempus mauris'),(33,'scelerisque neque. Nullam nisl. Maecenas'),(41,'Aliquam rutrum lorem ac'),(101,'sit amet metus.'),(50,'vel, venenatis vel, faucibus'),(70,'orci lobortis augue'),(15,'diam at pretium aliquet, metus');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(11,'Quisque varius. Nam porttitor scelerisque'),(76,'Etiam imperdiet dictum'),(5,'aliquet, sem ut cursus luctus,'),(52,'magna tellus faucibus leo, in'),(31,'condimentum. Donec at'),(66,'massa rutrum magna. Cras'),(95,'felis, adipiscing fringilla, porttitor vulputate,'),(89,'posuere cubilia Curae;'),(81,'nulla magna, malesuada vel,'),(58,'Fusce dolor quam,');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(46,'malesuada id, erat.'),(59,'molestie in, tempus eu, ligula.'),(96,'Donec egestas. Aliquam nec'),(83,'Aliquam tincidunt, nunc ac mattis'),(99,'non sapien molestie orci'),(5,'interdum enim non'),(30,'Proin non massa'),(87,'sagittis. Duis gravida. Praesent'),(63,'diam eu dolor egestas'),(46,'nulla ante, iaculis nec,');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(31,'vulputate velit eu sem.'),(36,'sem eget massa.'),(36,'lacus, varius et, euismod'),(44,'a purus. Duis elementum, dui'),(87,'amet orci. Ut'),(78,'facilisis eget, ipsum. Donec'),(56,'diam nunc, ullamcorper'),(100,'nascetur ridiculus mus.'),(65,'eleifend. Cras sed leo. Cras'),(28,'eu metus. In lorem.');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(17,'consectetuer euismod est arcu ac'),(26,'gravida mauris ut mi. Duis'),(98,'Duis elementum, dui quis'),(61,'urna. Vivamus molestie dapibus'),(26,'mollis. Duis sit amet'),(98,'iaculis quis, pede.'),(33,'scelerisque neque sed'),(19,'ridiculus mus. Aenean eget magna.'),(84,'Nam porttitor scelerisque neque. Nullam'),(5,'nulla. Donec non justo. Proin');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(30,'laoreet, libero et tristique pellentesque,'),(49,'gravida nunc sed pede. Cum'),(95,'elit. Nulla facilisi.'),(48,'ullamcorper eu, euismod ac,'),(21,'mi felis, adipiscing fringilla, porttitor'),(49,'pellentesque. Sed dictum.'),(76,'elit erat vitae'),(89,'Sed dictum. Proin eget odio.'),(78,'dui, nec tempus mauris erat'),(78,'orci. Ut sagittis lobortis mauris.');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(32,'magna. Cras convallis'),(44,'laoreet lectus quis massa.'),(26,'lobortis, nisi nibh lacinia orci,'),(96,'nunc sit amet metus.'),(48,'lorem ut aliquam'),(12,'nec mauris blandit'),(42,'massa rutrum magna. Cras'),(58,'Fusce diam nunc, ullamcorper'),(51,'tristique pellentesque, tellus sem'),(6,'arcu. Curabitur ut odio');
INSERT INTO ContactsOthers([ContactId],[Other]) VALUES(71,'a, scelerisque sed, sapien.'),(102,'eget metus eu'),(21,'Maecenas libero est,'),(21,'est. Nunc ullamcorper, velit'),(52,'consequat, lectus sit amet'),(68,'Vestibulum ut eros'),(31,'sed consequat auctor,'),(83,'sem magna nec quam.'),(88,'fermentum convallis ligula. Donec'),(61,'lacus. Quisque purus sapien, gravida');
